### ISSUE TITLE
CSS style guide

### ISSUE THREAD

**Issue by achisholm** [BBC-News/feedback#9]
Do you have a style guide written to document your CSS/SASS naming conventions and formatting?

**Comment by lwilkins** [comment]
Hi

We do have a style guide, but it is currently only available privately although this may change in the future.

To help answer your question though, we do make use of Sass (with SCSS syntax) and follow a version of the BEM naming convention for our classes. We also make use of https://github.com/causes/scss-lint and use a lot of the defaults it provides.
